name: Build App Preview
on:
  push:
    branches:
      - 'master'
jobs:
  build_android:
    name: Build APK
    type: build
    params:
      platform: android
      profile: preview
  build_ios:
    name: Build iOS Simulator
    type: build
    params:
      platform: ios
      profile: preview
